spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aipms
    username: aipms
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 87ef519c45789429b2f3826968e5abb9
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - friends
              - talk_message
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.aipms.domain

  configuration:
    map-underscore-to-camel-case: true

encrypt:
  secret-key: MySuperSecretKey1234567890123456

ai:
  server:
    url: http://localhost:5001